version: '3.7'

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ci/local/app.env

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
