"""Updating to use fast-api users

Revision ID: 2d2648db3223
Revises: a819ccb557c1
Create Date: 2023-09-03 10:20:24.205972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2648db3223'
down_revision: Union[str, None] = 'a819ccb557c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_attempt_user_id_fkey', 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempt', 'user', ['user_id'], ['id'])
    op.drop_constraint('slot_user_id_fkey', 'slot', type_='foreignkey')
    op.create_foreign_key(None, 'slot', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'NORMAL', 'ADVISOR', name='userrole'), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(length=320), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'salt')
    op.drop_column('user', 'uid')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('uid', sa.INTEGER(), server_default=sa.text("nextval('user_uid_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'role')
    op.drop_column('user', 'id')
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.create_foreign_key('slot_user_id_fkey', 'slot', 'user', ['user_id'], ['uid'])
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key('quiz_attempt_user_id_fkey', 'quiz_attempt', 'user', ['user_id'], ['uid'])
    # ### end Alembic commands ###
