"""Updating to use v5 ERD

Revision ID: a819ccb557c1
Revises: 0fab20d92393
Create Date: 2023-08-29 12:22:09.670772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a819ccb557c1'
down_revision: Union[str, None] = '0fab20d92393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('question_response',
    sa.Column('quiz_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.uid'], ),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempt.uid'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.uid'], ),
    sa.PrimaryKeyConstraint('quiz_attempt_id', 'question_id', 'response_id')
    )
    op.drop_table('subject')
    op.add_column('question', sa.Column('question', sa.String(), nullable=False))
    op.drop_column('question', 'question_str')
    op.add_column('quiz_attempt', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('quiz_attempt', sa.Column('subjects', sa.String(), nullable=False))
    op.create_foreign_key(None, 'quiz_attempt', 'user', ['user_id'], ['uid'])
    op.add_column('slot', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'slot', 'user', ['user_id'], ['uid'])
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.drop_column('slot', 'user_id')
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.drop_column('quiz_attempt', 'subjects')
    op.drop_column('quiz_attempt', 'user_id')
    op.add_column('question', sa.Column('question_str', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('question', 'question')
    op.create_table('subject',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uid', name='subject_pkey')
    )
    op.drop_table('question_response')
    op.drop_table('response')
    # ### end Alembic commands ###
